name: blog
description: 블로그 올릴거

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^9.4.0
  get: ^4.6.1
  provider: ^6.0.2

  #파이어스토어
  cloud_firestore: ^3.1.11

  #푸시 메시지
  firebase_messaging: ^11.2.12

  webview_flutter: ^3.0.2
  flutter_inappwebview: ^5.3.2
  flutter_app_badger: ^1.4.0
  
  # 파이어베이스 및 구글 로그인
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.16
  google_sign_in: ^5.3.0

  #  구글 캘린더
  syncfusion_flutter_calendar: ^20.1.51
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  
  #날짜
  intl: ^0.17.0

  #테이블 캘린더
  table_calendar: ^3.0.5

  #하이브
  hive: ^2.1.0
  hive_generator: ^1.1.2
  build_runner: ^2.1.10
  hive_flutter: ^1.1.0

  #권한 요청
  permission_handler: ^9.2.0

  #이미지 조작
  extended_image: ^6.2.0

  #아이콘에 숫자오르는거
  badges: ^2.0.2

  #아이콘
  font_awesome_flutter: ^10.1.0

  #아이폰처럼 반짝이는 그거 할때
  shimmer: ^2.0.0

  #sms 읽기
  flutter_sms_inbox: ^1.0.1

  #클립보드 사용
  clipboard: ^0.1.3

  #카카오 로그인, 톡, 스토리, 링크, 내비 사용가능한 전체 SDK 자세한건 https://developers.kakao.com/docs/latest/ko/getting-started/sdk-flutter 참조
#  kakao_flutter_sdk: ^1.1.1
  kakao_flutter_sdk_user: ^1.1.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
