name: blog
description: 블로그 올릴거

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_local_notifications: ^9.4.0

  #상태관리
  get: ^4.6.1
  provider: ^6.0.2

  #파이어스토어
  cloud_firestore: ^3.1.11

  #푸시 메시지
  firebase_messaging: ^11.2.12

  webview_flutter: ^3.0.2
  flutter_inappwebview: ^5.3.2
  flutter_app_badger: ^1.4.0
  
  # 파이어베이스 및 구글 로그인
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.16
  google_sign_in: ^5.3.0

  #  구글 캘린더
  syncfusion_flutter_calendar: ^20.1.51
  googleapis: ^8.1.0
  googleapis_auth: ^1.3.0
  
  #날짜
  intl: ^0.17.0

  #테이블 캘린더
  table_calendar: ^3.0.5

  #하이브
  hive: ^2.1.0
  hive_generator: ^1.1.2
  hive_flutter: ^1.1.0

  #권한 요청
  permission_handler: ^9.2.0

  #이미지 조작
  extended_image: ^6.2.0

  #아이콘에 숫자오르는거
  badges: ^2.0.2

  #아이콘
  font_awesome_flutter: ^10.1.0

  #아이폰처럼 반짝이는 그거 할때
  shimmer: ^2.0.0

  #sms 읽기
  flutter_sms_inbox: ^1.0.1

  #클립보드 사용
  clipboard: ^0.1.3

  #카카오 로그인, 톡, 스토리, 링크, 내비 사용가능한 전체 SDK 자세한건 https://developers.kakao.com/docs/latest/ko/getting-started/sdk-flutter 참조
  #kakao_flutter_sdk: ^1.1.1
  kakao_flutter_sdk_user: ^1.1.1

  #http통신
  http: ^0.13.4
#  flutter_naver_map: ^0.10.5
  #네이버 지도 연동
  naver_map_plugin:
    git: https://github.com/LBSTECH/naver_map_plugin.git

  #디바이스 위치
  geolocator: ^8.2.1

  #폰 진동낼수 있음
  vibration: ^1.7.3

  #일정 거리 내의 누가 있나 확인하는거
  geofencing: ^0.1.0

  #백그라운드 서비스 이용
  flutter_background_service: ^2.1.2

  #기기 정보
  device_info_plus: ^3.2.4

  #영상 출력 - 기본적인 거만 지원 유튜브처럼 하려면 추가 패키지를 쓰거나 UI 직접 제작
  video_player: ^2.4.4

  #실시간 음성 및 영상 통화 - agora 사용해야함(유료)
  agora_rtc_engine: ^5.2.0

  #https://pub.dev/packages/rtmp_publisher 여기는 무료로 rtmp를 사용할 수 있나봄

  #실시간 음성 및 영상 통화 - 무료
  flutter_webrtc: ^0.8.9

  #소켓 통신
  socket_io_client: ^1.0.2
  socket_io: ^1.0.1

  #NFC 읽는거
  nfc_manager: ^3.1.1
  fluttertoast: ^8.0.9

  #model json으로 바꿀 때 쓰는 거
  json_annotation: ^4.6.0

  #앱 버전확인
  new_version: ^0.3.1

  #Flutter와 Mux를 이용한 서버리스 라이브 스트리밍 앱  https://blog.flutterflow.io/flutter-mux-live-streaming/ 이건 돈땜시 못함

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.1
  flutter_lints: ^1.0.0
  #자동 생성용 뭐시기
  build_runner: ^2.2.0
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true

  assets:
    - assets/
